apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cogstack-opensearch.fullname" . }}-opensearch-config
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
data:
  opensearch.yml: |
{{ .Files.Get "files/opensearch.yml" | indent 4 }}
  log4j2.properties: |
{{ .Files.Get "files/log4j2.properties" | indent 4 }}
