{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogstack-opensearch.credentialsSecretName" . }}
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ .Values.credentials.adminPassword | quote }}
  KIBANA_USER: {{ .Values.credentials.kibanaUser | quote }}
  KIBANA_PASSWORD: {{ .Values.credentials.kibanaPassword | quote }}
{{- end }}
