network.host: 0.0.0.0


###### CLUSTER CONFIGURATION ######

# To allow multiple nodes add the node's IP addresses to the discovery pool. 
# ["<private IP of opensearch-d1>", "<private IP of opensearch-d2>", "<private IP of opensearch-c1>"]
discovery.seed_hosts: ["127.0.0.1", "elasticsearch-2", "elasticsearch-1"]

# # Details: https://github.com/elastic/elasticsearch/pull/17288
# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# discovery.zen.minimum_master_nodes: 2


######## Start OpenDistro for Elasticsearch Security Demo Configuration ########
# WARNING: revise all the lines below before you go into production
plugins.security.ssl.transport.pemcert_filepath: esnode.pem
plugins.security.ssl.transport.pemkey_filepath: esnode.key
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
#plugins.security.ssl.http.enabled: true

plugins.security.ssl.http.pemcert_filepath: esnode.pem
plugins.security.ssl.http.pemkey_filepath: esnode.key
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
#plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de
#  - 'CN=cogstack' 

plugins.security.nodes_dn:
  - 'CN=elasticsearch-*'

plugins.security.audit.type: internal_elasticsearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]

node.max_local_storage_nodes: 3
######## End OpenDistro for Elasticsearch Security Demo Configuration ########