# Some of these parameters are provided by the Docker environment variables
server.name: kibana
server.host: "0"
# INFO: ES URL provided as docker parameter
#opensearch.hosts: ['https://localhost:9200']
opensearch.ssl.verificationMode: none

# WARNING: revise all the lines below before you go into production
opensearch.username: kibanaserver
opensearch.password: kibanaserver
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
